name: Upload Python Package

# Trigger on push to main branch and manual invocation
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Required for OpenID Connect (OIDC) token exchange for trusted publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Step 3: Install dependencies for building and publishing
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine

      # Step 4: Build the package distributions
      - name: Build distributions
        run: |
          python -m build

      # Step 5: Publish to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
