name: Upload Python Package

# Trigger the workflow on any push to the repository or manual invocation
on:
  push:
    branches:
      - main  # Adjust to your default branch if it's not 'main'
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Step 3: Install dependencies for building the package
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build

      # Step 4: Build the distributions
      - name: Build release distributions
        run: |
          python -m build

      # Step 5: Publish directly to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          password: ${{ secrets.PYPI_API_TOKEN }}
